### ISSUE TITLE
Error on Search DB Fasta IDs that do not contain a space character

### ISSUE THREAD

**Issue by jj-umn** [cwenger/Morpheus#13]
Morpheus/Morpheus/Protein.cs  
public string Accession
        {
            get { return Description.Substring(0, Description.IndexOf(' ')); }
        }
Causes an exception if a fasta ID line doesn't contain a space character.  Finding accessions is difficult due to the wide range of formatting in use. Compomics attempts to pattern all common  formats in order to find the Accession: https://github.com/compomics/compomics-utilities/blob/master/src/main/java/com/compomics/util/protein/Header.java

At the minimum, it might be good to return the entire Description as the accession if a space character is not found.

**Comment by cwenger** [comment]
I just pushed the latter solution and it will be included in the next release. Let me know if you need the binaries sooner.

**Comment by jj-umn** [comment]
We're mostly using the Uniprot.xml format.   But with fasta I'm having users pipe through a regex that guarantees a space character in the ID line as a temporary work around.  
Thanks.
