### ISSUE TITLE
mzIdentML EnzymeName with cvParam

### ISSUE THREAD

**Issue by jj-umn** [cwenger/Morpheus#14]
I was trying to use ProteoWizard idconvert to convert the Morpheus mzid output to pep.xml for pyQuant.  
idconvert expects an EnzymeName tag with a cvParam.  

The Morpheus maid has:
<Enzymes>
  <Enzyme id="E" name="trypsin (no proline rule)" semiSpecific="false" missedCleavages="2" />
</Enzymes>

% idconvert -o outdir2 --pepXML morpheus.mzid
    format: pepXML
    outputPath: outdir2
    extension: .pepXML

```
filenames:
  morpheus.mzid

processing file: morpheus.mzid
writing output file: outdir2/morpheus.pepXML
Error writing analysis 1 in "morpheus.mzid":
[pepXMLSpecificity] No case supporting enzyme "CVID_Unknown"
```

idconvert succeeds if I edit morpheus.mzid to add the EnzymeName tag:
<Enzymes>
  <Enzyme id="E" name="trypsin (no proline rule)" semiSpecific="false" missedCleavages="2">
    <EnzymeName>
      <cvParam accession="MS:1001313" name="Trypsin/P" cvRef="PSI-MS"/> 
    </EnzymeName>
  </Enzyme>
</Enzymes>

**Comment by cwenger** [comment]
Added EnzymeName and SiteRegexp nodes (read from proteases.tsv) to mzIdentML output. Updated proteases.tsv with this data from PSI-MS. This should fix the idconvert error.
