### ISSUE TITLE
FDR implementation / Q-Values

### ISSUE THREAD

**Issue by straussmaximilian** [cwenger/Morpheus#20]
Hi,
I am trying to understand your implementation of the FDR cutoff / q-value calculation. When attempting to calculate the cutoff myself, I end up with higher thresholds.
I see that Morpheus cuts based on the q-value.  Naively, I would have assumed that q_value = FDR, with FDR = N_decoy / N_total = N_decoy / (N_decoy+N_target). However, when I plot the q-values from vs this definition from the tsv output sheet  I see that that the values differ:
![01_fdr_vs](https://user-images.githubusercontent.com/16521288/55401355-bf7e9780-5550-11e9-929d-e89cdccb6d2d.png)

For my specific example I get the following results from the Morpheus log (FDR = 0.01):
`14,276 target (142 decoy) PSMs at 0.994% PSM FDR (12.062 Morpheus score threshold)`
From the table I can see where the cut is made:
![Screen Shot 2019-04-02 at 2 11 08 PM](https://user-images.githubusercontent.com/16521288/55401475-2d2ac380-5551-11e9-999a-ab9cbf2fb38a.png)

Here, the FDR is calculated as 142/(14276+142) = 0.0098488 which is different than the q-value. However, even for the last value, the FDR would be 143/(14279+143) = 0.0099154 and therefore < 0.01, giving you a couple more hits.
Is the definition of the q-value another or is this a bug? Any help on this would be appreciated. Thank you so much.

**Comment by cwenger** [comment]
Hi Maximilian,

I'm using the definition FDR = N_decoy / N_target. The other definition
I've heard is FDR = 2 * N_decoy / (N_decoy + N_target), but that doesn't
make sense if you are not reporting decoys as true matches.

Also, I use a rule that q-value cannot decrease as score decreases. So if
you are progressing through descending scores, if you have a decoy match
that spikes your q-value above 1%, subsequent target matches cannot reduce
your q-value below 1%. I'm not sure if this is a formal rule anywhere that
others use, but it seems logical to me to be conservative when reporting
matches.

-Craig

**Comment by zrolfs** [comment]
Adding on to Craig's response: the FDR and q-value are the same, and are calculated as: (false-positives) / (true-positives + false-positives). Note that this is not the same as decoys/(targets+decoys), but rather decoys/targets. The reason for this is that some number of the target hits are incorrect, and thus the number of targets is inherently the sum of the true- and false-positive identifications. The number of decoys is simply a proxy for the number of false-positive targets identified, and is not part of the total.

**Comment by straussmaximilian** [comment]
Hi,
Thank you for your swift response - things are much clearer now. I also had tried decoys/targets, but they were not the same - the missing link was the decreasing q-value-rule. So thanks again.

Here I have one more question: Within the code, I found this:

![Screen Shot 2019-04-02 at 4 46 42 PM](https://user-images.githubusercontent.com/16521288/55412037-fe1f4c80-5566-11e9-83fe-a50b02034c84.png)

As your aim is to be conservative, shouldn't this be the other way around? As you are decreasing from the right side a potentially larger q-value will be made smaller.

When plotting decoy/target vs. q-value, it looks like this:

![test03](https://user-images.githubusercontent.com/16521288/55411240-9288af80-5565-11e9-8c74-d55c044e9415.png)

Thanks again.

**Comment by cwenger** [comment]
You're right--that's what I get for replying without checking the code to
see what it actually does. I am using the q-value definition given by Käll
et al. in https://noble.gs.washington.edu/papers/kall2008assigning.pdf: "the
minimal FDR threshold at which a given PSM is accepted". Your figure is
like Figure 4B in that paper, rotated 90 degrees.

-Craig

**Comment by straussmaximilian** [comment]
Thanks a lot. This paper is a great resource.
