### ISSUE TITLE
It is awesome that you are still maintaining Morpheus!!!

### ISSUE THREAD

**Issue by trishorts** [cwenger/Morpheus#22]
if you have any interest in seeing the minor tweaks we made to it over the years, stop by
https://github.com/smith-chem-wisc/MetaMorpheus

i hope you are doing well. luv to hear what you are up to.
-michael

**Comment by cwenger** [comment]
I wouldn't say I am still maintaining it, but I do make a change here or there. I am very happy to see how MetaMorpheus has flourished. Hope you are doing well also!
